version: "2"

services:
  db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 89a89a89aiG_
      MYSQL_DATABASE: tripify
      MYSQL_PASSWORD: 89a89a89aiG_
      MYSQL_ROOT_HOST: '%'
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    expose:
      - "3306"
    networks:
      default:
        aliases:
          - db.local

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ${APP_PATH}/client:/client

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "12345:12345"
    volumes:
      - ${APP_PATH}/server:/server

